package autosell.vistas.artigos;

import autosell.gestores.GestorEstabelecimentos;
import autosell.modelos.Artigo;
import autosell.modelos.Estabelecimento;
import javax.swing.SpinnerNumberModel;

public class JanelaEnviarArtigo extends javax.swing.JDialog {

    private Artigo artigo;
    private Artigo artigoAEnviar;

    public JanelaEnviarArtigo(Artigo artigo) {
        initComponents();
        setLocationRelativeTo(null);
        toolBarMenu.setFloatable(false);

        if (artigo == null) {
            throw new NullPointerException("Não é possível enviar um artigo inesxistente.");
        }

        this.artigo = artigo;

        loadEstabelecimentos();

        spinnerQuantidade.setModel(new SpinnerNumberModel(0, 0, artigo.getQuantidadeAtual(), 1));
        textFieldUnidade.setText(artigo.getUnidade());
    }

    private void loadEstabelecimentos() {
        var estabelecimentos = GestorEstabelecimentos.getInstance().getListagem();

        estabelecimentos.remove(artigo.getEstabelecimento());

        for (Estabelecimento estabelecimento : estabelecimentos) {
            comboBoxEstabelecimento.addItem(estabelecimento);
        }
    }

    public Artigo showDialog() {
        setVisible(true);
        return artigoAEnviar;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolBarMenu = new javax.swing.JToolBar();
        buttonEnviar = new javax.swing.JButton();
        panelEdicao = new javax.swing.JPanel();
        labelQuantidade = new javax.swing.JLabel();
        labelUnidade = new javax.swing.JLabel();
        textFieldUnidade = new javax.swing.JTextField();
        labelEstabelecimento = new javax.swing.JLabel();
        comboBoxEstabelecimento = new javax.swing.JComboBox<>();
        spinnerQuantidade = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        buttonEnviar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autosell/Resources/cube-send.png"))); // NOI18N
        buttonEnviar.setText("Enviar");
        buttonEnviar.setFocusable(false);
        buttonEnviar.setMaximumSize(new java.awt.Dimension(80, 52));
        buttonEnviar.setMinimumSize(new java.awt.Dimension(80, 52));
        buttonEnviar.setPreferredSize(new java.awt.Dimension(80, 52));
        buttonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEnviarActionPerformed(evt);
            }
        });
        toolBarMenu.add(buttonEnviar);

        panelEdicao.setBackground(new java.awt.Color(255, 255, 255));

        labelQuantidade.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelQuantidade.setText("Quantidade");

        labelUnidade.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelUnidade.setText("Unidade");

        textFieldUnidade.setEditable(false);
        textFieldUnidade.setEnabled(false);
        textFieldUnidade.setName("Unidade"); // NOI18N

        labelEstabelecimento.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelEstabelecimento.setText("Estabelecimento");

        spinnerQuantidade.setName("Quantidade"); // NOI18N

        javax.swing.GroupLayout panelEdicaoLayout = new javax.swing.GroupLayout(panelEdicao);
        panelEdicao.setLayout(panelEdicaoLayout);
        panelEdicaoLayout.setHorizontalGroup(
            panelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEdicaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelEstabelecimento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelEdicaoLayout.createSequentialGroup()
                        .addGroup(panelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spinnerQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelUnidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textFieldUnidade)))
                    .addComponent(comboBoxEstabelecimento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelEdicaoLayout.setVerticalGroup(
            panelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEdicaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelQuantidade)
                    .addComponent(labelUnidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinnerQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelEstabelecimento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboBoxEstabelecimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toolBarMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
            .addComponent(panelEdicao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(toolBarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelEdicao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEnviarActionPerformed
        artigoAEnviar = new Artigo(
                artigo.getReferencia(),
                artigo.getNome(),
                0,
                Float.parseFloat(spinnerQuantidade.getValue().toString()),
                artigo.getUnidade(),
                (Estabelecimento) comboBoxEstabelecimento.getSelectedItem());

        setVisible(false);
        dispose();
    }//GEN-LAST:event_buttonEnviarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonEnviar;
    private javax.swing.JComboBox<Estabelecimento> comboBoxEstabelecimento;
    private javax.swing.JLabel labelEstabelecimento;
    private javax.swing.JLabel labelQuantidade;
    private javax.swing.JLabel labelUnidade;
    private javax.swing.JPanel panelEdicao;
    private javax.swing.JSpinner spinnerQuantidade;
    private javax.swing.JTextField textFieldUnidade;
    private javax.swing.JToolBar toolBarMenu;
    // End of variables declaration//GEN-END:variables
}
