package autosell.Vistas;

import autosell.Utils.TableModel;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.List;
import java.util.regex.PatternSyntaxException;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.RowFilter;
import javax.swing.event.ListSelectionEvent;
import javax.swing.table.TableRowSorter;

public abstract class JanelaListagem extends javax.swing.JInternalFrame {

    protected JTable table;
    protected TableRowSorter<TableModel> tableRowSorter;
    protected int[] tableColumnIndex;
    protected TableModel tableModel;

    public JanelaListagem() {
        this("");
    }
    
    public JanelaListagem(String nomeJanela) {
        initComponents();
        setTitle(nomeJanela);
    }

    protected void initTableComponents(String[] columnNames, Object[][] tableData) {
        tableModel = new TableModel(columnNames, tableData);
        tableRowSorter = new TableRowSorter<>(tableModel);
        table = new JTable(tableModel);

        if (tableData.length == 0) {
            return;
        }

        table.setRowSorter(tableRowSorter);
        table.setPreferredScrollableViewportSize(new Dimension(500, 70));
        table.setFillsViewportHeight(true);
        table.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        table.getSelectionModel().addListSelectionListener(this::selecaoAlterada);

        panelTable.add(table);

        JScrollPane scrollPane = new JScrollPane(table);
        panelTable.add(scrollPane);

        tableColumnIndex = tableModel.getColumnIndexes();
    }

    private void selecaoAlterada(ListSelectionEvent e) {
        int viewRow = table.getSelectedRow();

        if (viewRow > 0) {
            table.convertRowIndexToModel(viewRow);
        }
    }

    private void aplicarFiltro(String criterio) {

        RowFilter<TableModel, Object> rowFilter = null;

        if (criterio == null || criterio.length() == 0) {
            tableRowSorter.setRowFilter(rowFilter);
            return;
        }

        String[] textToSearchSplitted = criterio.split(" ");

        List<RowFilter<TableModel, Object>> listOfRowFilters = new ArrayList<>();

        try {
            for (String textToSearchSplitted1 : textToSearchSplitted) {

                String regexToSearch = new StringBuilder("(?i)")
                        .append(textToSearchSplitted1).toString();

                listOfRowFilters.add(RowFilter.regexFilter(regexToSearch, tableColumnIndex));
            }

            rowFilter = RowFilter.andFilter(listOfRowFilters);

        } catch (PatternSyntaxException e) {
            return;
        }

        tableRowSorter.setRowFilter(rowFilter);
    }

    protected abstract void acaoRemover();

    protected abstract void acaoSelecionar();
    
    protected abstract void acaoAtualizar();

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolBarMenu = new javax.swing.JToolBar();
        buttonSelecionar = new javax.swing.JButton();
        separator1 = new javax.swing.JToolBar.Separator();
        buttonPesquisar = new javax.swing.JButton();
        textFieldPesquisar = new javax.swing.JTextField();
        buttonLimpar = new javax.swing.JButton();
        separator2 = new javax.swing.JToolBar.Separator();
        buttonAtualizar = new javax.swing.JButton();
        separator3 = new javax.swing.JToolBar.Separator();
        buttonRemover = new javax.swing.JButton();
        panelTable = new javax.swing.JPanel();

        setClosable(true);
        setMinimumSize(new java.awt.Dimension(700, 517));

        buttonSelecionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autosell/Resources/checkbox-marked-outline.png"))); // NOI18N
        buttonSelecionar.setText("Selecionar");
        buttonSelecionar.setFocusable(false);
        buttonSelecionar.setMaximumSize(new java.awt.Dimension(100, 52));
        buttonSelecionar.setMinimumSize(new java.awt.Dimension(100, 52));
        buttonSelecionar.setPreferredSize(new java.awt.Dimension(100, 52));
        buttonSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSelecionarActionPerformed(evt);
            }
        });
        toolBarMenu.add(buttonSelecionar);
        toolBarMenu.add(separator1);

        buttonPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autosell/Resources/magnify.png"))); // NOI18N
        buttonPesquisar.setFocusable(false);
        buttonPesquisar.setLabel("Pesquisar");
        buttonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPesquisarActionPerformed(evt);
            }
        });
        toolBarMenu.add(buttonPesquisar);

        textFieldPesquisar.setMaximumSize(new java.awt.Dimension(150, 32));
        textFieldPesquisar.setMinimumSize(new java.awt.Dimension(150, 32));
        textFieldPesquisar.setName(""); // NOI18N
        textFieldPesquisar.setPreferredSize(new java.awt.Dimension(150, 32));
        toolBarMenu.add(textFieldPesquisar);

        buttonLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autosell/Resources/backspace.png"))); // NOI18N
        buttonLimpar.setText("Limpar");
        buttonLimpar.setFocusable(false);
        buttonLimpar.setMaximumSize(new java.awt.Dimension(76, 32));
        buttonLimpar.setMinimumSize(new java.awt.Dimension(76, 32));
        buttonLimpar.setPreferredSize(new java.awt.Dimension(76, 32));
        buttonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLimparActionPerformed(evt);
            }
        });
        toolBarMenu.add(buttonLimpar);
        toolBarMenu.add(separator2);

        buttonAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autosell/Resources/autorenew.png"))); // NOI18N
        buttonAtualizar.setText("Atualizar");
        buttonAtualizar.setFocusable(false);
        buttonAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAtualizarActionPerformed(evt);
            }
        });
        toolBarMenu.add(buttonAtualizar);
        toolBarMenu.add(separator3);

        buttonRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autosell/Resources/trash-can.png"))); // NOI18N
        buttonRemover.setText("Remover");
        buttonRemover.setFocusable(false);
        buttonRemover.setMaximumSize(new java.awt.Dimension(82, 52));
        buttonRemover.setMinimumSize(new java.awt.Dimension(82, 52));
        buttonRemover.setPreferredSize(new java.awt.Dimension(82, 52));
        buttonRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRemoverActionPerformed(evt);
            }
        });
        toolBarMenu.add(buttonRemover);

        panelTable.setBackground(new java.awt.Color(255, 255, 255));
        panelTable.setName("panelTable"); // NOI18N
        panelTable.setLayout(new java.awt.GridLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toolBarMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
            .addComponent(panelTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(toolBarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelTable, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSelecionarActionPerformed
        acaoSelecionar();
    }//GEN-LAST:event_buttonSelecionarActionPerformed

    private void buttonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPesquisarActionPerformed
       aplicarFiltro(textFieldPesquisar.getText());
    }//GEN-LAST:event_buttonPesquisarActionPerformed

    private void buttonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLimparActionPerformed
       textFieldPesquisar.setText("");
       aplicarFiltro("");
    }//GEN-LAST:event_buttonLimparActionPerformed

    private void buttonAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAtualizarActionPerformed
        acaoAtualizar();
    }//GEN-LAST:event_buttonAtualizarActionPerformed

    private void buttonRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRemoverActionPerformed
        acaoRemover();
    }//GEN-LAST:event_buttonRemoverActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAtualizar;
    private javax.swing.JButton buttonLimpar;
    private javax.swing.JButton buttonPesquisar;
    private javax.swing.JButton buttonRemover;
    private javax.swing.JButton buttonSelecionar;
    private javax.swing.JPanel panelTable;
    private javax.swing.JToolBar.Separator separator1;
    private javax.swing.JToolBar.Separator separator2;
    private javax.swing.JToolBar.Separator separator3;
    private javax.swing.JTextField textFieldPesquisar;
    private javax.swing.JToolBar toolBarMenu;
    // End of variables declaration//GEN-END:variables
}
