package autosell.Vistas;

import autosell.Gestores.Gestor;
import autosell.Utils.AppLogger;
import autosell.Utils.TableModel;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import java.util.function.Predicate;
import java.util.regex.PatternSyntaxException;
import javax.swing.ListSelectionModel;
import javax.swing.RowFilter;
import javax.swing.event.ListSelectionEvent;
import javax.swing.table.TableRowSorter;


public class JanelaSelecao<T>  extends javax.swing.JDialog {
    private Gestor<T> gestor;
    private TableRowSorter<TableModel> tableRowSorter;
    private TableModel tableModel;
    private LinkedList<T> resultList;
    private Predicate<T> predicate;
    
    public JanelaSelecao(String nomeJanela, Gestor<T> gestor, boolean multipleSelection){
        this(nomeJanela, gestor, null, multipleSelection);
    }

    public JanelaSelecao(String nomeJanela, Gestor<T> gestor, Predicate<T> predicate, boolean multipleSelection) {
        this.gestor = gestor;
        this.predicate = predicate;
        resultList = new LinkedList<>();
        
        initComponents();
        setTitle(nomeJanela);
        
        String[] columns = new String[]{ "", "Obj"};
        tableModel = new TableModel(columns, getTableData());
        table.setModel(tableModel);
        tableRowSorter = new TableRowSorter<>(tableModel);
        
        table.getColumnModel().getColumn(1).setMinWidth(0);
        table.getColumnModel().getColumn(1).setMaxWidth(0);
        table.getColumnModel().getColumn(1).setWidth(0);
        table.setSelectionMode(multipleSelection ? ListSelectionModel.MULTIPLE_INTERVAL_SELECTION : ListSelectionModel.SINGLE_SELECTION);
        table.getSelectionModel().addListSelectionListener(this::selecaoAlterada);
    }
    
    private Object[][] getTableData(){
        var listagem = predicate == null ? gestor.getListagem() : gestor.getListagem(predicate);
        var aux = new Object[listagem.size()][2];
        
        int i = 0;
        for (T t : listagem) {
            aux[i][0] = t.toString();
            aux[i][1] = t;
            i++;
        }
        return aux;
    }
    
    private void selecaoAlterada(ListSelectionEvent e) {
        int viewRow = table.getSelectedRow();

        if (viewRow > 0) {
            table.convertRowIndexToModel(viewRow);
        }
    }
    
    private void aplicarFiltro(String criterio) {

        RowFilter<TableModel, Object> rowFilter = null;

        if (criterio == null || criterio.length() == 0) {
            tableRowSorter.setRowFilter(rowFilter);
            return;
        }

        String[] textToSearchSplitted = criterio.split(" ");

        List<RowFilter<TableModel, Object>> listOfRowFilters = new ArrayList<>();

        try {
            for (String textToSearchSplitted1 : textToSearchSplitted) {

                String regexToSearch = new StringBuilder("(?i)")
                        .append(textToSearchSplitted1).toString();

                listOfRowFilters.add(RowFilter.regexFilter(regexToSearch, 1));
            }

            rowFilter = RowFilter.andFilter(listOfRowFilters);

        } catch (PatternSyntaxException e) {
            return;
        }

        tableRowSorter.setRowFilter(rowFilter);
    }

    private void acaoAtualizar() {
        try {
            tableModel.setData(getTableData());
        } catch (Exception e) {
            AppLogger.LOG.warning(this, e);
        }
    }
    
    public LinkedList<T> showDialog(){
        setVisible(true);
        return resultList;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolBarMenu = new javax.swing.JToolBar();
        buttonSelecionar = new javax.swing.JButton();
        separator1 = new javax.swing.JToolBar.Separator();
        buttonPesquisar = new javax.swing.JButton();
        textFieldPesquisar = new javax.swing.JTextField();
        buttonLimpar = new javax.swing.JButton();
        separator2 = new javax.swing.JToolBar.Separator();
        buttonAtualizar = new javax.swing.JButton();
        separator3 = new javax.swing.JToolBar.Separator();
        scroolPaneTable = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setModal(true);

        buttonSelecionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autosell/Resources/checkbox-marked-outline.png"))); // NOI18N
        buttonSelecionar.setText("Selecionar");
        buttonSelecionar.setFocusable(false);
        buttonSelecionar.setMaximumSize(new java.awt.Dimension(100, 52));
        buttonSelecionar.setMinimumSize(new java.awt.Dimension(100, 52));
        buttonSelecionar.setPreferredSize(new java.awt.Dimension(100, 52));
        buttonSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSelecionarActionPerformed(evt);
            }
        });
        toolBarMenu.add(buttonSelecionar);
        toolBarMenu.add(separator1);

        buttonPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autosell/Resources/magnify.png"))); // NOI18N
        buttonPesquisar.setFocusable(false);
        buttonPesquisar.setLabel("Pesquisar");
        buttonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPesquisarActionPerformed(evt);
            }
        });
        toolBarMenu.add(buttonPesquisar);

        textFieldPesquisar.setMaximumSize(new java.awt.Dimension(150, 32));
        textFieldPesquisar.setMinimumSize(new java.awt.Dimension(150, 32));
        textFieldPesquisar.setName(""); // NOI18N
        textFieldPesquisar.setPreferredSize(new java.awt.Dimension(150, 32));
        toolBarMenu.add(textFieldPesquisar);

        buttonLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autosell/Resources/backspace.png"))); // NOI18N
        buttonLimpar.setText("Limpar");
        buttonLimpar.setFocusable(false);
        buttonLimpar.setMaximumSize(new java.awt.Dimension(76, 32));
        buttonLimpar.setMinimumSize(new java.awt.Dimension(76, 32));
        buttonLimpar.setPreferredSize(new java.awt.Dimension(76, 32));
        buttonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLimparActionPerformed(evt);
            }
        });
        toolBarMenu.add(buttonLimpar);
        toolBarMenu.add(separator2);

        buttonAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autosell/Resources/autorenew.png"))); // NOI18N
        buttonAtualizar.setText("Atualizar");
        buttonAtualizar.setFocusable(false);
        buttonAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAtualizarActionPerformed(evt);
            }
        });
        toolBarMenu.add(buttonAtualizar);
        toolBarMenu.add(separator3);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        table.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        table.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        table.setShowGrid(false);
        scroolPaneTable.setViewportView(table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toolBarMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(scroolPaneTable)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(toolBarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scroolPaneTable, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSelecionarActionPerformed

        for(int row : table.getSelectedRows()){
            resultList.add((T) table.getValueAt(row, 1));
        }
        
        setVisible(false);
        dispose();
    }//GEN-LAST:event_buttonSelecionarActionPerformed

    private void buttonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPesquisarActionPerformed
        aplicarFiltro(textFieldPesquisar.getText());
    }//GEN-LAST:event_buttonPesquisarActionPerformed

    private void buttonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLimparActionPerformed
        textFieldPesquisar.setText("");
        aplicarFiltro("");
    }//GEN-LAST:event_buttonLimparActionPerformed

    private void buttonAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAtualizarActionPerformed
        acaoAtualizar();
    }//GEN-LAST:event_buttonAtualizarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAtualizar;
    private javax.swing.JButton buttonLimpar;
    private javax.swing.JButton buttonPesquisar;
    private javax.swing.JButton buttonSelecionar;
    private javax.swing.JScrollPane scroolPaneTable;
    private javax.swing.JToolBar.Separator separator1;
    private javax.swing.JToolBar.Separator separator2;
    private javax.swing.JToolBar.Separator separator3;
    private javax.swing.JTable table;
    private javax.swing.JTextField textFieldPesquisar;
    private javax.swing.JToolBar toolBarMenu;
    // End of variables declaration//GEN-END:variables
}
