package autosell.Vistas.Colaboradores;

import autosell.Modelos.Colaborador;
import autosell.Utils.TableModel;
import javax.swing.JTable;
import javax.swing.table.TableRowSorter;


public class JanelaEditarColaborador extends javax.swing.JInternalFrame {
    private Colaborador colaborador;
    protected JTable table;
    protected TableRowSorter<TableModel> tableRowSorter;
    protected int[] tableColumnIndex;
    protected TableModel tableModel;
    
    public JanelaEditarColaborador() {
        this(null);
    }
    
    public JanelaEditarColaborador(Colaborador colaborador) {
        this.colaborador = colaborador;
        initComponents();
        
        // TODO: Carregar a listagem de todos os estabelecimentos
        // TODO: Popular os dados do colaborador
        // TODO: Carregar a listagem de vendas do colaborador
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolBarMenu = new javax.swing.JToolBar();
        buttonGuardar = new javax.swing.JButton();
        panelEdicao = new javax.swing.JPanel();
        labelNome = new javax.swing.JLabel();
        textFieldNome = new javax.swing.JTextField();
        textFieldEmail = new javax.swing.JTextField();
        labelEmail = new javax.swing.JLabel();
        labelEstabelecimento = new javax.swing.JLabel();
        comboBoxEstabelecimento = new javax.swing.JComboBox<>();
        labelPasswordAntiga = new javax.swing.JLabel();
        passwordFieldPasswordAntiga = new javax.swing.JPasswordField();
        passwordFieldNovaPassword = new javax.swing.JPasswordField();
        labelVendas = new javax.swing.JLabel();
        passwordFieldConfirmNovaPassword = new javax.swing.JPasswordField();
        labelConfirmNovaPassword = new javax.swing.JLabel();
        labelNovaPassword = new javax.swing.JLabel();
        panelVendas = new javax.swing.JPanel();
        labelToBeImplemented = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setTitle("Editar Colaborador");
        setToolTipText("");

        buttonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autosell/Resources/content-save.png"))); // NOI18N
        buttonGuardar.setText("Guardar");
        buttonGuardar.setFocusable(false);
        buttonGuardar.setMaximumSize(new java.awt.Dimension(80, 52));
        buttonGuardar.setMinimumSize(new java.awt.Dimension(80, 52));
        buttonGuardar.setPreferredSize(new java.awt.Dimension(80, 52));
        buttonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGuardarActionPerformed(evt);
            }
        });
        toolBarMenu.add(buttonGuardar);

        panelEdicao.setBackground(new java.awt.Color(255, 255, 255));

        labelNome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelNome.setText("Nome");

        labelEmail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelEmail.setText("E-mail");

        labelEstabelecimento.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelEstabelecimento.setText("Estabelecimento");

        labelPasswordAntiga.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelPasswordAntiga.setText("Password Antiga");

        labelVendas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelVendas.setText("Vendas");

        labelConfirmNovaPassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelConfirmNovaPassword.setText("Confirmação Nova Password");

        labelNovaPassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelNovaPassword.setText("Nova Password");

        panelVendas.setBackground(new java.awt.Color(255, 255, 255));
        panelVendas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelVendas.setLayout(new java.awt.GridBagLayout());

        labelToBeImplemented.setText("To be Implemented...");
        panelVendas.add(labelToBeImplemented, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout panelEdicaoLayout = new javax.swing.GroupLayout(panelEdicao);
        panelEdicao.setLayout(panelEdicaoLayout);
        panelEdicaoLayout.setHorizontalGroup(
            panelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEdicaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEdicaoLayout.createSequentialGroup()
                        .addGroup(panelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(passwordFieldPasswordAntiga, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                                .addComponent(textFieldNome)
                                .addComponent(labelNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(labelPasswordAntiga))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(passwordFieldNovaPassword, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(textFieldEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                                .addComponent(labelEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(labelNovaPassword))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboBoxEstabelecimento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(passwordFieldConfirmNovaPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                            .addComponent(labelEstabelecimento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelConfirmNovaPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panelEdicaoLayout.createSequentialGroup()
                        .addComponent(labelVendas)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(panelVendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelEdicaoLayout.setVerticalGroup(
            panelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEdicaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(panelEdicaoLayout.createSequentialGroup()
                            .addComponent(labelEmail)
                            .addGap(0, 0, 0)
                            .addGroup(panelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(textFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(comboBoxEstabelecimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(panelEdicaoLayout.createSequentialGroup()
                            .addComponent(labelNome)
                            .addGap(0, 0, 0)
                            .addComponent(textFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(labelEstabelecimento))
                .addGap(18, 18, 18)
                .addGroup(panelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(panelEdicaoLayout.createSequentialGroup()
                        .addComponent(labelPasswordAntiga)
                        .addGap(0, 0, 0)
                        .addComponent(passwordFieldPasswordAntiga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelEdicaoLayout.createSequentialGroup()
                        .addComponent(labelNovaPassword)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(passwordFieldNovaPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelEdicaoLayout.createSequentialGroup()
                        .addComponent(labelConfirmNovaPassword)
                        .addGap(0, 0, 0)
                        .addComponent(passwordFieldConfirmNovaPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(labelVendas)
                .addGap(0, 0, 0)
                .addComponent(panelVendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEdicao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(toolBarMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(toolBarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelEdicao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGuardarActionPerformed
        
    }//GEN-LAST:event_buttonGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonGuardar;
    private javax.swing.JComboBox<String> comboBoxEstabelecimento;
    private javax.swing.JLabel labelConfirmNovaPassword;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelEstabelecimento;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelNovaPassword;
    private javax.swing.JLabel labelPasswordAntiga;
    private javax.swing.JLabel labelToBeImplemented;
    private javax.swing.JLabel labelVendas;
    private javax.swing.JPanel panelEdicao;
    private javax.swing.JPanel panelVendas;
    private javax.swing.JPasswordField passwordFieldConfirmNovaPassword;
    private javax.swing.JPasswordField passwordFieldNovaPassword;
    private javax.swing.JPasswordField passwordFieldPasswordAntiga;
    private javax.swing.JTextField textFieldEmail;
    private javax.swing.JTextField textFieldNome;
    private javax.swing.JToolBar toolBarMenu;
    // End of variables declaration//GEN-END:variables
}
